# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=150, null=True, verbose_name='链接')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='标题')),
                ('tag', models.CharField(max_length=5, verbose_name='新闻标签')),
                ('abstract', models.CharField(max_length=500, verbose_name='概述')),
                ('keyword', models.CharField(max_length=100, verbose_name='关键字')),
                ('content', models.TextField(blank=True, null=True, verbose_name='正文')),
                ('click_nums', models.IntegerField(blank=True, default=0, null=True, verbose_name='点击次数')),
                ('create_time', models.DateTimeField(verbose_name='时间')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
            },
        ),
    ]
