# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.CharField(default=None, max_length=500, verbose_name='喜好'),
        ),
    ]
