# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-12 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='interests',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='model',
            field=models.TextField(blank=True, null=True, verbose_name='用户兴趣模型'),
        ),
    ]
