# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-17 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userinterest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinterest',
            options={'verbose_name': '兴趣模型', 'verbose_name_plural': '兴趣模型'},
        ),
    ]
