# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-23 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180417_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinterest',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserInterest',
        ),
    ]
